### ISSUE TITLE
Render some storyboards at 4:3 ratio

### ISSUE THREAD

**Issue by blueberrymuffin3** [blueberrymuffin3/osu-js#21]
Some beatmaps, including [Renai Circulation mapped by taka1235](https://osu-js.pages.dev/play/?37714), are rendered at a 4:3 aspect ratio by osu!stable. 
- [x] Determine what flag/option decides this
- [x] Implement in osu-parsers or osu-storyboard-parser
- [x] Mask these maps in osu-js

**Comment by kionell** [comment]
I think you are looking for `WidescreenStoryboard` option. It can be found in the [general section](https://osu.ppy.sh/wiki/en/Client/File_formats/Osu_%28file_format%29#general) of a beatmap. This option is already [parsed](https://github.com/kionell/osu-parsers/blob/master/src/Decoders/Handlers/Beatmaps/GeneralDecoder.ts#L88) by osu-parsers
