### ISSUE TITLE
Add support for storyboard overlay layer

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#24]
This layer is used to display storyboard objects on the front. The main difference between the foreground layer and the overlay layer is that the overlay layer is rendered on top of everything, even over the hit objects and HP bar.

Here are some beatmaps with overlay layer objects:
https://osu.ppy.sh/beatmapsets/1485845#osu/3046792
https://osu.ppy.sh/beatmapsets/1391659#osu/2873429

**Comment by blueberrymuffin3** [comment]
Thanks! I've been meaning to add it, but I couldn't find any beatmaps that actually used it.
