### ISSUE TITLE
Fix start time for animations

### ISSUE THREAD

**Issue by blueberrymuffin3** [blueberrymuffin3/osu-js#29]
https://github.com/blueberrymuffin3/osu-js/blob/4a8f72ac353fdb8e3ffb79f06aa5add735d5cfba/src/play/game/storyboard_timeline.ts#L396-L397

Causes issues for many storyboards including [world.execute(me); - Mili](https://osu-js.pages.dev/play/?1006822) and [Oedo Controller (feat. TORIENA)](https://osu-js.pages.dev/play/?1610972)

- [x] Blocked by #26

**Comment by kionell** [comment]
I found out that [danser](https://github.com/Wieku/danser-go/blob/master/app/storyboard/storyboard.go)  doesn't have this issue. Wieku uploaded [this](https://youtu.be/vduOWtkPH-M?t=76) video about 8 months ago.

**Comment by kionell** [comment]
@blueberrymuffin3 I finally fixed this!!! It appears that [osu-classes](https://github.com/kionell/osu-classes/blob/master/src/Storyboards/Commands/CommandTimelineGroup.ts#L65) and [osu!](https://github.com/ppy/osu/blob/master/osu.Game/Storyboards/CommandTimelineGroup.cs#L70) itself replace starting time of the sprites with starting time of the first fade command if its start value is 0. I immediately thought about this when i didn't found anything related to fade commands in the dancer's source code. 

https://user-images.githubusercontent.com/43014304/184201366-972c16be-00d6-4967-9cd2-d826255aefc2.mp4
