### ISSUE TITLE
Time Traveler's `rewind` animation is not working

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#33]
And again, [Time Traveler](https://osu-js.pages.dev/play/?2573493). In the beatmap folder you can find `time travel` dir with the `rewind` animation. It doesn't play for some reason, and I don't think it's render lag because the cursor moves smoothly.

**Comment by blueberrymuffin3** [comment]
I believe that this is at least partially due to #29

**Comment by kionell** [comment]
The bug fixed itself after switching to `osu-parsers`

**Comment by blueberrymuffin3** [comment]
The rewind animation is offset in time due to #29
