### ISSUE TITLE
Some beatmaps download without video

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#39]
Beatmap: https://kitsu.moe/d/762823 

It seems to be related directly to `kitsu.moe`. Perhaps this requires replacing the beatmap mirror, but which one to use instead?

**Comment by blueberrymuffin3** [comment]
This appears to be a geographical issue. In the US, it redirects to a host that downloads with the video (`us.kitsu.moe`), but in europe, it downloads without video (`kitsu.moe`).

**Comment by blueberrymuffin3** [comment]
@kionell Can you confirm that fix this works from your location?

**Comment by kionell** [comment]
Yep, it seems to be fixed now
