### ISSUE TITLE
Remuxed videos "stutter" while playing

### ISSUE THREAD

**Issue by blueberrymuffin3** [blueberrymuffin3/osu-js#40]
Both the original (avi) and remuxed (mp4) videos play fine in both mpv and vlc, but when the remuxed video is played in either chrome or firefox, the frames appear to be shown out-of-order. This may have something to do with ffmpeg messing up the PTS and DTS of b-frames, but I'm not sure. Native mp4 videos, which are not remuxed, play fine in both firefox and chrome.

Example: https://osu-js.pages.dev/play/?1643958

**Comment by blueberrymuffin3** [comment]
Seems similar to https://video.stackexchange.com/questions/22340/ffmpeg-repackaging-avi-h264-into-mp4-gives-choppy-playback-in-html5-video-on-c

This issue persists with the latest version of FFMPEG (ffmpeg/ffmpeg@d3f48e68b3, osu-js uses [4.3.1](https://github.com/blueberrymuffin3/ffmpeg.wasm-core/)), so if it's a bug in ffmpeg it hasn't been fixed.

**Comment by kionell** [comment]
I investigated this problem a little bit and came to the conclusion that using `libx264` codec can help you with #22 and this one. I have tested beatmap from the example above and didn't notice any stutters. However, in exchange for using this codec, you have to sacrifice the speed of video conversion. If you want to use your own fork of the ffmpeg/core, you must re-enable `libx264`.

```js
    await ffmpeg.run(
      "-i", ffmpegInputFilename,
      "-c:v", "libx264",
      "-c:a", "copy",
      "-preset", "ultrafast",
      "-an",
      "output.mp4"
    );
```

**Comment by blueberrymuffin3** [comment]
I've been trying to avoid re-encoding the video since it can take a while, but I might have to resort to it. I'm currently looking into using FFmpeg as a software decoder and writing a custom device to send the decoded video to webgl, which would also solve #22.
