### ISSUE TITLE
Decode audio file before starting

### ISSUE THREAD

**Issue by blueberrymuffin3** [blueberrymuffin3/osu-js#45]
Currently, the audio is decoded either [here](https://github.com/blueberrymuffin3/osu-js/blob/4637ce98721d8b1ff47982ce86d3fa02e0180102/src/play/game/standard_game.ts#L49) or [here](https://github.com/blueberrymuffin3/osu-js/blob/4637ce98721d8b1ff47982ce86d3fa02e0180102/src/play/game/standard_game.ts#L106-L108).

The decoding can take many seconds for longer songs.

**Comment by kionell** [comment]
I have a fix for this issue, but it's based on another sound library named [Howler](https://github.com/goldfire/howler.js/). If you don't mind replacing pixi/sound then i can make pull request for you.
