### ISSUE TITLE
Use osu!standard ruleset package to get additional data

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#5]
I have already done most of your work related to osu!std objects. You should definitely try to use my [osu-standard-stable](https://github.com/kionell/osu-standard-stable) package. This may help you with object stacking, combo indexes and other stuff. 
Also, cool project. Are you planning to finish it? This could be a great browser extension that I wouldn't mind using. But I think of it more as a renderer than a full game. TBH there are no good quality beatmap renderer that is available for browsers (except one from bloodcat, but it mostly dead??). Since you have the ability to parse beatmaps in a browser, you can also try to add support for custom .osu files.

**Comment by blueberrymuffin3** [comment]
Thanks!
I'll definitely look into using osu-standard-stable, it sounds super useful.
I was thinking about turning it into a web-based replay viewer or an extension for a "preview" button for beatmaps.
