### ISSUE TITLE
iOS Safari throws error 4 on audio loading

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#54]
Jeez, this browser is so dumb... I can't even find where this error is happening, because it just throws 4 as a number... Through trial and error, I figured out that it's something related to [Howler's onloaderror event](https://github.com/goldfire/howler.js#onloaderror-function). I have no idea how to fix this.

![image](https://user-images.githubusercontent.com/43014304/184501237-863493e0-6355-4992-ac7d-5a7b5c8bbbd9.png)

**Comment by blueberrymuffin3** [comment]
I think the 4 may actually be the sound ID. The error handler is currently mistaking it for the error message. Unfortunately, I don't have access to an iphone to test on atm, so I can't reproduce.

**Comment by blueberrymuffin3** [comment]
Nevermind, it seems like that is the actual error code. I make the error less cryptic in f677ada0a067eefea9cb0be1619934bda8c2e23f.

**Comment by kionell** [comment]
Disabling HTML5 audio for iOS devices fixes this problem. I need to ask my friend to test it on his iPhone.

```ts
loaded.audio = await loadSound({
  src: (await blobUrlFromFile(audioFile)) as string,
  html5: !isUsingIOS,
  preload: !isUsingIOS ? "metadata" : true,
  format: audioFile.name.substring(
    audioFile.name.lastIndexOf(".") + 1
  ),
});
````

**Comment by kionell** [comment]
@blueberrymuffin3 Audio now loads correctly on iOS.
