### ISSUE TITLE
Slider path sometimes disappears on mobile Chrome

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#8]
This only happens on my phone and almost on all beatmaps that i tried. I don't really know what's the reason for this behaviour and how to reproduce it. The only thing is that it happens every time on the same beatmap even after restarting. 

https://osu-js.pages.dev/play/?1315750 - One of the beatmaps with this problem.

Here's a video that shows what's wrong (it's in slow motion because the render lags when recording the screen).

https://user-images.githubusercontent.com/43014304/180645072-8d4a7869-b806-4472-a839-0dfb2bc27081.mp4

**Comment by blueberrymuffin3** [comment]
Oh weird, I've never seen that before. I'll look into it.

**Comment by blueberrymuffin3** [comment]
It seems to have something to do with precision, as adding `precision highp float;` to both shaders fixes the issue...

**Comment by blueberrymuffin3** [comment]
@kionell Can you confirm that this issue has been fixed on your device?

**Comment by kionell** [comment]
@blueberrymuffin3 I just tested some beatmaps that had disappearing sliders and none of them have this issue anymore.

**Comment by blueberrymuffin3** [comment]
@kionell Awesome, thanks!
